### PR TITLE
Added title + author name guidelines to example.

### PR DESCRIPTION
**Pull request by avandeursen**
In the drafts I've seen so far, title or author names were forgotten.

To emphasize that each chapter has authors, I've updated the example chapter.

For a title, make sure you mention the name of the system you're analyzing, and an optional short, engaging statement of what it is. ("The Architecture of GitHub: a Social Coding Site").

### CODE REVIEW

**Comment by rogierslag** [comment]
Might also want to update the Jekyll front matter at the top of the file with an appealing title

**Comment by avandeursen** [comment]
What do you mean @rogierslag?

**Comment by rogierslag** [comment]
I mean [this line](https://github.com/delftswa/delftswa.github.io/pull/7/files#diff-cea5e5da8dd80a7792ca44c3d6ecc841R4) since that is how the project will be shown. For me that doesnt necessarily have to be the project name, as long as the chapter name clearly identifies which project it is about

**Comment by rogierslag** [comment]
:+1:

**Pull request merged**
